name       : python-podcastparser
version    : 0.6.2
release    : 2
source     :
    - https://github.com/gpodder/podcastparser/archive/0.6.2.tar.gz : 8e6b33d88d78bf4ca8085e135f6c736039169916580b9c256b80b6af536ce79b
license    : ISC
component  : programming.python
summary    : Simple, fast and efficient podcast parser
description: |
    A library from the gPodder project to provide an easy and reliable way of parsing RSS- and Atom-based podcast feeds in Python.
builddeps  :
    - python-coverage
    - python-nose
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        nosetests-3.5 -v
    popd
