name       : python-podcastparser
version    : 0.6.9
release    : 11
source     :
    - https://github.com/gpodder/podcastparser/archive/refs/tags/0.6.9.tar.gz : ee15f020a24b3b5a05f3edf44571dcd22fbc33da064b701d7b40e811d6a1509f
homepage   : https://github.com/gpodder/podcastparser
license    : ISC
component  : programming.python
summary    : Simple, fast and efficient podcast parser
description: |
    A library from the gPodder project to provide an easy and reliable way of parsing RSS- and Atom-based podcast feeds in Python.
builddeps  :
    - python-pytest-cov
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
