name       : python-podcastparser
version    : 0.6.6
release    : 8
source     :
    - https://github.com/gpodder/podcastparser/archive/0.6.6.tar.gz : b36adead23adb138aa12504740d8b875c2eda581bd72cdcb18a579cb5e1ec2fb
homepage   : https://github.com/gpodder/podcastparser
license    : ISC
component  : programming.python
summary    : Simple, fast and efficient podcast parser
description: |
    A library from the gPodder project to provide an easy and reliable way of parsing RSS- and Atom-based podcast feeds in Python.
builddeps  :
    - python-pytest-cov
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
